USE [Shared]
GO
CREATE SCHEMA [Reports]
GO
CREATE TABLE [Reports].[DosReportsBASE]
(
	[ReportKEY]  [VARCHAR](255)  NOT NULL,
	[ReportJSON] [NVARCHAR](MAX) NOT NULL,
	[StatusCD]   [VARCHAR](255)  NOT NULL DEFAULT 'Active',
	CONSTRAINT [pkDosReportsBASE] PRIMARY KEY CLUSTERED ([ReportKEY] ASC)
) ON [HCSharedData1]
GO